name: Tectum 4.0 public blockchain publisher

on:
  push:
    branches:
    - main

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    timeout-minutes: 15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CSharp/Tectum.PublicBlockChainClient

    - name: Build
      run: dotnet build --configuration Release --no-restore CSharp/Tectum.PublicBlockChainClient
      
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --configuration Release --no-build CSharp/Tectum.PublicBlockChainClient

    - name: Create pack
      run: dotnet pack --configuration Release --no-build --output . CSharp/Tectum.PublicBlockChainClient
           
    - name: Push nuget.org
      run: dotnet nuget push *.nupkg --api-key ${NUGET_TOKEN} --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        
    - name: Push to nuget.pkg.github.com
      run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/crispmindltd/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES }}
   
